#pragma once
/*******************************************************************
Author: David Ge (dge893@gmail.com, aka Wei Ge)
Last modified: 11/21/2020
Allrights reserved by David Ge

compare simulation data generated by the Radius Indexing simulator and the Cubic Indexing simulator
********************************************************************/
#include "../EMField/RadiusIndex.h"
#include "../EMField/EMField.h"
#include "../EMField/FieldSource.h"
class RadiusCubic :
	virtual public GoThroughSphereByIndexes
{
private:
	Point3Dstruct *E;
	Point3Dstruct *H;
	FieldPoint3D *EH;
	FieldsInitializer *fiv;
	FieldSource *fs;
	double ds;
	double maxErr;
protected:
	virtual void handleData(int m, int n, int p);
public:
	RadiusCubic();
	~RadiusCubic();
	double MaxError(){ return maxErr; }
	void SetFields(Point3Dstruct *ef, Point3Dstruct*hf, FieldPoint3D *ehf, FieldsInitializer* iv, FieldSource *src, double step);
};

