#pragma once
/*******************************************************************
Author: David Ge (dge893@gmail.com, aka Wei Ge)
Last modified: 11/21/2020
Allrights reserved by David Ge

make field data statistics by radius, the data are generated by the Cubic Indexing simulator
********************************************************************/

#include "../EMField/RadiusIndex.h"
#include "../EMField/EMField.h"
#include "../TssInSphere/FieldStatistics.h"
#include "../Tss/Tss.h"
#include "../Tss/Simulator.h"
class RadiusStatistics :public virtual GoThroughSphereByIndexes
{
private:
	Point3Dstruct *efile;
	Point3Dstruct *hfile;
	Simulator *sim;
	FieldStatistics fs;
	unsigned int nx1, ny1, nz1;  //nx1=nx+1; ny1=ny+1; nz1=nz+1
	//
protected:
	virtual RadiusHandleType setRadius(int radius);
	virtual void handleData(int m, int n, int p);
public:
	RadiusStatistics();
	~RadiusStatistics();
	size_t Idx(unsigned i, unsigned j, unsigned k);
	//
	int initialize(Point3Dstruct *fE, Point3Dstruct *fH, unsigned int maxR, Simulator *tsssim);
	int writeStatisticsToFile(FILE *filehandle);
};

